### PR TITLE
Download and use clojure-lsp instead of built-in initialize

### LINKED ISSUE #25: LSP stuck on Initializing
When I enable the Clojure LSP plugin or press the "restart" button in the settings (cf. https://github.com/clojure-lsp/clojure-lsp-intellij/blob/e017810ac2041c4d9c7804e684b74d0f18300206/docs/troubleshooting.md) I get an additional "Clojure LSP startup" background task, but the server never actually starts. "Copy server info to clipboard" gives me `nil`. `ps aux` does not list any process with `lsp` in its name, either.

image
image

```
IntelliJ IDEA 2023.2.2 (Ultimate Edition)
Build #IU-232.9921.47, built on September 12, 2023
Licensed to [REDACTED]
You have a perpetual fallback license for this version.
Subscription is active until [REDACTED].
Runtime version: 17.0.8+7-b1000.22 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.4.15-200.fc38.x86_64
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    editor.minimap.enabled=true

Non-Bundled Plugins:
    com.jetbrains.plugins.ini4idea (232.9921.55)
    com.jetbrains.rust (232.9921.62)
    org.intellij.plugins.hcl (232.8660.88)
    com.intellij.plugins.watcher (232.8660.88)
    org.jetbrains.plugins.go-template (232.9921.62)
    com.intellij.ideolog (222.1.0.0)
    name.kropp.intellij.makefile (232.8660.88)
    org.jetbrains.plugins.localization (232.8660.88)
    org.jetbrains.plugins.go (232.9921.28)
    com.github.clojure-lsp (0.12.4)
    com.intellij.kubernetes (232.9921.28)
    com.intellij.grazie.pro (0.3.250)
    com.intellij.datagen (232.8660.88)
    PlantUML integration (7.0.0-IJ2023.2)
    com.demonwav.minecraft-dev (2023.2-1.6.10)
    com.dmarcotte.handlebars (232.8660.88)
    com.intellij.tide (232.8660.88)
    Pythonid (232.9921.47)
    com.intellij.bigdatatools.core (232.9921.47)
    com.intellij.bigdatatools.binary.files (232.8660.206)
    com.intellij.bigdatatools.rfs (232.9921.47)
    mobi.hsz.idea.gitignore (4.5.1)
    com.cursiveclojure.cursive (1.13.0-2023.2)
    com.github.brcosta.cljstuffplugin (0.7.9)
    to.bri.intellij.clubhouse (0.1.13)
    nix-idea (0.4.0.10)
    net.ashald.envfile (3.4.1)
    com.jetbrains.php (232.9921.55)
    aws.toolkit (1.79-232)

Kotlin: 232-1.9.0-IJ9921.47
Current Desktop: KDE
```

Note that I do also have Cursive enabled and that (as far as I can tell from `Settings > Editor > File Types > Clojure, ClojureScript and ClojureDart`, which I believe is the Clojure LSP plugin's file type) Cursive, providing the "Clojure file" section, still holds the `*.clj` files, which are the only files in this project.

### PR DESCRIPTION
**Pull request by ericdallo**
Fixes #25 #26 and #29
This will be a major change as it changes the core of the plugin on how to communicate with the server

### CODE REVIEW

**Comment by ericdallo** [comment]
[Uploading clojure-lsp-1.14.10.zip…]()

**Comment by ericdallo** [comment]
v2: 
[clojure-lsp-1.14.10.zip](https://github.com/clojure-lsp/clojure-lsp-intellij/files/14498968/clojure-lsp-1.14.10.zip)

**Comment by ericdallo** [comment]
v3: [clojure-lsp-1.14.10.zip](https://github.com/clojure-lsp/clojure-lsp-intellij/files/14499970/clojure-lsp-1.14.10.zip)

**Comment by ericdallo** [comment]
v4: 
[clojure-lsp-1.14.10.zip](https://github.com/clojure-lsp/clojure-lsp-intellij/files/14510337/clojure-lsp-1.14.10.zip)

**Comment by ericdallo** [comment]
v5:
[Uploading clojure-lsp-1.14.10.zip…]()

@abreumatheus please, try this one, it fixes that problem

**Comment by ericdallo** [comment]
v6: 
[clojure-lsp-1.14.10.zip](https://github.com/clojure-lsp/clojure-lsp-intellij/files/14515789/clojure-lsp-1.14.10.zip)


@abreumatheus could you try this one please?

**Comment by ericdallo** [comment]
v7: [clojure-lsp-1.14.10.zip](https://github.com/clojure-lsp/clojure-lsp-intellij/files/14525343/clojure-lsp-1.14.10.zip)

**Comment by ericdallo** [comment]
Latest version (same on current master)[clojure-lsp-2.0.0.zip](https://github.com/clojure-lsp/clojure-lsp-intellij/files/14529853/clojure-lsp-2.0.0.zip)

**Comment by mefryar** [comment]
> Latest version (same on current master)[clojure-lsp-2.0.0.zip](https://github.com/clojure-lsp/clojure-lsp-intellij/files/14529853/clojure-lsp-2.0.0.zip)

When I install Clojure LSP from this ZIP, I get the following error when initializing IntelliJ. I realize maybe I just need to wait until the update is available via the IntelliJ Plugin Marketplace. But wanted to flag in case it is helpful.
```
java.io.FileNotFoundException: https://github.com/clojure-lsp/clojure-lsp/releases/download/2024.03.01-11.37.51/null
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1996)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at java.base/java.net.URL.openStream(URL.java:1161)
	at clojure.java.io$fn__11621.invokeStatic(io.clj:239)
	at clojure.java.io$fn__11621.invoke(io.clj:235)
	at clojure.java.io$fn__11569$G__11523__11576.invoke(io.clj:69)
	at clojure.java.io$fn__11629.invokeStatic(io.clj:256)
	at clojure.java.io$fn__11629.invoke(io.clj:254)
	at clojure.java.io$fn__11569$G__11523__11576.invoke(io.clj:69)
	at clojure.java.io$input_stream.invokeStatic(io.clj:136)
	at clojure.java.io$input_stream.doInvoke(io.clj:121)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at com.github.clojure_lsp.intellij.server$download_server_BANG_.invokeStatic(server.clj:77)
	at com.github.clojure_lsp.intellij.server$download_server_BANG_.invoke(server.clj:67)
	at com.github.clojure_lsp.intellij.server$start_server_BANG_$fn__21205.invoke(server.clj:146)
	at com.github.clojure_lsp.intellij.tasks$run_background_task_BANG_$run21108_impl__21110.invoke(tasks.clj:16)
	at com.github.clojure_lsp.intellij.tasks.proxy_plus21107.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

> macOS 14.3.1
> IntelliJ IDEA 2023.3.4 (Community Edition)
> clojure-lsp-intellij 2.0.0

**Comment by ericdallo** [comment]
Thanks, @abreumatheus @mefryar, Could you try this one:
If not working, could you get the result of:
```
clj
> (System/getProperty "os.name" "generic")
``` 

and 

```
(System/getProperty "os.arch")
```

**Comment by ericdallo** [comment]
Got the problem, it happens with macos non aarch64, this one should fix:
[clojure-lsp-2.0.0.zip](https://github.com/clojure-lsp/clojure-lsp-intellij/files/14539600/clojure-lsp-2.0.0.zip)

**Comment by mefryar** [comment]
It works! 🎉 Confirming that all of https://github.com/clojure-lsp/clojure-lsp-intellij/issues/25 https://github.com/clojure-lsp/clojure-lsp-intellij/issues/26 and https://github.com/clojure-lsp/clojure-lsp-intellij/issues/29 now seem to be fixed for me. 👏

**Pull request merged**
